const Data = {
  Options: [
    {
      Option: "Sobre mi",
      hash: "#about",
      id: "about",
    },
    {
      Option: "Servicios",
      hash: "#study",
      id: "study",
    },
    {
      Option: "Educacion",
      hash: "#education",
      id: "education",
    },
    {
      Option: "Certificaciones",
      hash: "#certification",
      id: "certification",
    },
    {
      Option: "Talleres",
      hash: "#workshops",
      id: "workshops",
    },
    {
      Option: "Profesional",
      hash: "#experience",
      Option_complete: "Practica - Profesional",
      id: "experience",
    },
    {
      Option: "Habilidades",
      hash: "#skills",
      id: "skills",
    },
    {
      Option: "Proyectos",
      hash: "#projects",
      id: "projects",
    },
  ],
  About: [
    {
      Name: "Angel",
      LastName: "Mora",
      First_NickName: "An",
      logo: "./multimedia/Nll_LllMllTS.png",
      Code_Postal: "10201",
      Address: "Urb. La Nuez",
      Direction: "San Antonio de Escazu",
      Telephone: "(+506) 7254-7757",
      email: "anmora.2396@gmail.com",
      descripcion: "Desarrollador Software Web",
      animation: '</Desarrollador Web ',
      presentacion:
        "Capaz de autogestión eficaz en proyectos independientes, me fascina todo lo que aprendo y aplico en cada proyecto que desarrollo. Trabajar con proyectos nuevos es mi pasión.",
      resumen:
        "Aspirante a desarrollador de software web MERN Full Stack, creación, diseño, gestión y mantenimiento de software computacional.",
      tiempo_libre: "",
      invitacion1:
        "Te invito a ver mi portafolio y si te gustó, hazme saber usando la primera opción del menú lateral ",
      invitacion2: " o por si deseas comunicarte conmigo.",
      invite: "'Enviar Correo'",  
      links: [
        {
          title: "Direction",
          name: "San José, Escazú",
          istarget: "No",
          target: "",
          icon: "fas fa-map-marker-alt",
          link: "##",
        },
        {
          title: "Telephone",
          name: "(+506) 7254 7757",
          istarget: "No",
          target: "",
          icon: "fas fa-mobile-alt",
          link: "##",
        },
        {
          title: "Descargar CV",
          name: "Descargar CV",
          istarget: "Si",
          target: "_blank",
          icon: "fas fa-file-download",
          link: "./Documentos/CVAnMora.pdf",
        },
        {
          title: "Linkeldin",
          name: "Linkeldin",
          istarget: "Si",
          target: "_blank",
          icon: "fab fa-linkedin-in",
          link: "https://www.linkedin.com/in/anmora-angel-mora",
        },
        {
          title: "GitHub",
          name: "GitHub",
          istarget: "Si",
          target: "_blank",
          icon: "fab fa-github",
          link: "https://github.com/AnMora",
        },
        {
          title: "Facebook",
          name: "Facebook",
          istarget: "Si",
          target: "_blank",
          icon: "fab fa-facebook-f",
          link: "https://www.facebook.com/an.mora011/",
        },
        // {
        //   title: "Slack",
        //   name: "(Slack) An Mora",
        //   istarget: "No",
        //   target: "",
        //   icon: "fab fa-slack",
        //   link: "##",
        // },
      ],
      // Verificar los datos de google y realizar los cambios
      // Puede que por la migracion de GA4 hayan cambiado estos valores, verificar los datos
      service: "gmailMessage",
      template: "template_wrhn59m",
      user: "user_NmXDJbRWH1HpgirJoZskd",
      clientId:
        "820641787972-k7l8h3q7a4mt28maotjod30ffqirrq8l.apps.googleusercontent.com",
      trackingId: "UA-214885646-1",
      siteKey: "6LfELJEbAAAAAK2Z1EW1Liv48bC7rfJuEzE6cVWI",
      // ===================================================================================>
    },
  ],
  Study: [
    {
      Title: "Por que elegirme?",
      Project_by: "Desarrollador web con experiencia",
      Description:
        "Trabajo en conjunto para organizar tus ideas, desarrollo a la medida y llevar tu proyecto a la realidad.",
      img: "./multimedia/Certifications.jpg",
    },
  ],
  Education: [
    {
      Issuer: "4Geeks Academy",
      Title: "Full Stack Software Development FT",
      Issued_On_Day: "7",
      Issued_On_Month: "Abril",
      Issued_On_Year: "2021",
      Expired_On: "No caduca",
      Description:
        "Este documento certifica que el estudiante es un Desarrollador Web Full Stack, con un conocimiento competente para ayudar en la creación de aplicaciones web usando HTML / CSS, Javascript, React y REST API usando SQL, Python y Flask Framework.",
      Level: "No obtenido",
      Total_Hours: "380",
      link_name: "certificate.breatheco.de",
      link_verified:
        "https://certificate.breatheco.de/1bf82bc26776ac6a6874024e4a1b38312c563a60",
      Register_No: "No obtenido",
    },
    {
      Issuer: "Instituto Nacional de Aprendizaje",
      Title: "Desarrollo Web",
      Issued_On_Day: "10",
      Issued_On_Month: "Octubre",
      Issued_On_Year: "2019",
      Expired_On: "No caduca",
      Description:
        "Este documento certifica que el estudiante es un desarrollador web, otorgado por el Instituto Nacional de Aprendizaje (INA) por su conclusión exitosa en periodo de aprendizaje, con un conocimiento competente para ayudar en la creación de aplicaciones web usando lo aprendido en clases en resumen: levantamiento de requerimientos según el cliente, estudio e implementación de sitio web, minutas y establecimiento de acuerdo para desarrollo de software para/con los clientes, test case (casos de prueba), matriz de trazabilidad de requisitos, wireframing (wireframes) y prototyping (mockups), Brackets (Editor de código), Sublime Text 3 (Editor de codigo) Instalación de plugings, HTML 5, CSS 3, Bootstrap (framework), Fetch API en DATA JSON, manejo del DOM JavaScript con AJAX, Angular (breve aprendizaje), TypeScript (breve aprendizaje), WordPress (breve aprendizaje) y estudio e implementación sobre accesibilidad web.",
      Level: "Técnico",
      Total_Hours: "1594",
      link_name: "No obtenido",
      link_verified: "../../Documentos/Desarrollo_web.pdf",
      Register_No: "2418-01490-2019",
    },
    {
      Issuer: "Instituto Nacional de Aprendizaje",
      Title: "Comprension de lectura en ingles",
      Issued_On_Day: "19",
      Issued_On_Month: "Junio",
      Issued_On_Year: "2019",
      Expired_On: "No caduca",
      Description:
        "Este documento certifica que el estudiante ha concluido con éxito el módulo de Compresión de lectura de inglés, otorgado por el Instituto Nacional de Aprendizaje (INA) en periodo de aprendizaje y un conocimiento competente.",
      Level: "No obtenido",
      Total_Hours: "60",
      link_name: "No obtenido",
      link_verified: "../../Documentos/Comprension_de_lectura_en_ingles.pdf",
      Register_No: "2418-01049-2019",
    },
    {
      Issuer: "Instituto Nacional de Aprendizaje",
      Title: "Programador de Paginas Web",
      Issued_On_Day: "16",
      Issued_On_Month: "Marzo",
      Issued_On_Year: "2018",
      Expired_On: "No caduca",
      Description:
        "Este documento certifica que el estudiante es un programador de páginas web, otorgado por el Instituto Nacional de Aprendizaje (INA) por su conclusión exitosa en periodo de aprendizaje, con un conocimiento competente para ayudar en la creación de aplicaciones web usando lo aprendido en clases en resumen: Lógica Computacional (Algoritmos), Seudocódigo, Teoría de factores y fundamentos del diseño gráfico para web, HTML 4.1, CSS 3, Dreamweaver (IDE), Introducción DOM con JavaScript.",
      Level: "Técnico",
      Total_Hours: "294",
      link_name: "No obtenido",
      link_verified: "../../Documentos/Programador_de_paginas_web.pdf",
      Register_No: "2418-00349-2018",
    },
  ],
  Certifications: [
    {
      Issuer: "Udemy",
      Title: "JavaScript: Desde cero con NodeJS",
      Issued_On_Day: "13",
      Issued_On_Month: "Octubre",
      Issued_On_Year: "2023",
      Expired_On: "No caduca",
      Instructores: [{ Instructor: "DataBoosters Academy, Geovanny Gabriel" }],
      Description:
        "Este certificado garantiza que Ángel Mora Flores ha completado con éxito el curso JavaScript: Desde cero con NodeJS a fecha de 13/10/2023, habiendo sido impartido por DataBoosters Academy, Geovanny Gabriel en Udemy. El certificado indica que se ha completado la totalidad del curso, según lo validado por el estudiante. La duración del curso representa el total de horas de vídeo del curso en el momento de finalización más reciente.",
      Level: "No obtenido",
      Total_Hours: "12",
      Total_Classes: "63",
      link_name: "udemy.com/certificate",
      link_verified:
        "https://www.udemy.com/certificate/UC-57ae38b2-37ac-4f77-893b-dc57b897e861/",
      Register_No: "UC-57ae38b2-37ac-4f77-893b-dc57b897e861",
    },
    {
      Issuer: "CertiProf Professional Knowledge",
      Title: "Scrum Foundation Professional Certificate SFPC (v2020)",
      Issued_On_Day: "9",
      Issued_On_Month: "Marzo",
      Issued_On_Year: "2022",
      Expired_On: "No caduca",
      Instructores: [{ Instructor: "Bluelime Learning Solutions en Udemy" }],
      Description:
        "The Scrum Guide™, The Definitive Guide to Scrum: The Rules of the Game, desarrollada y sustentada por los fundadores de Scrum, Ken Schwaber y Jeff Sutherland, contiene la definición de Scrum, incluidos roles, eventos, artefactos y las reglas que vinculan ellos juntos.",
      Level: "No obtenido",
      Total_Hours: "No obtenido",
      Total_Classes: "No obtenido",
      link_name:
        "certiprof.com/pages/scrum-foundation-professional-certificate-sfpc-spanish",
      link_verified: "../../Documentos/Certificate.pdf",
      Register_No: "74457375",
    },
    {
      Issuer: "Udemy",
      Title: "Create a Business or Personal Website with Wordpress",
      Issued_On_Day: "12",
      Issued_On_Month: "Septiembre",
      Issued_On_Year: "2021",
      Expired_On: "No caduca",
      Instructores: [{ Instructor: "Bluelime Learning Solutions en Udemy" }],
      Description:
        "Este certificado garantiza que Ángel Mora Flores ha completado con éxito el curso Create a Business or Personal Website with Wordpress, habiendo sido impartido por Bluelime Learning Solutions en Udemy. El certificado indica que se ha completado la totalidad del curso, según lo validado por el estudiante. La duración del curso representa el total de horas de vídeo del curso en el momento de finalización más reciente.",
      Level: "No obtenido",
      Total_Hours: "3,5",
      Total_Classes: "33",
      link_name: "udemy.com/certificate",
      link_verified:
        "https://www.udemy.com/certificate/UC-bbeb27d5-9c9f-44d2-913a-9b235289efae/",
      Register_No: "UC-bbeb27d5-9c9f-44d2-913a-9b235289efae",
    },
    {
      Issuer: "Udemy",
      Title: "Full-Stack Web Development with React and MongoDB",
      Issued_On_Day: "24",
      Issued_On_Month: "Junio",
      Issued_On_Year: "2021",
      Expired_On: "No caduca",
      Instructores: [{ Instructor: "Chandan Kumar" }],
      Description:
        "Este certificado garantiza que Ángel Mora Flores ha completado con éxito el curso Full-Stack Web Development with React and MongoDB, habiendo sido impartido por Chandan Kumar en Udemy. El certificado indica que se ha completado la totalidad del curso, según lo validado por el estudiante. La duración del curso representa el total de horas de vídeo del curso en el momento de finalización más reciente.",
      Level: "No obtenido",
      Total_Hours: "5,5",
      Total_Classes: "54",
      link_name: "udemy.com/certificate",
      link_verified:
        "https://www.udemy.com/certificate/UC-aa12019a-08a7-409f-8980-5250e93a1ae4/",
      Register_No: "UC-aa12019a-08a7-409f-8980-5250e93a1ae4",
    },
    {
      Issuer: "Udemy",
      Title: "The Complete ReactJS Course - Basic to Advanced(2021)",
      Issued_On_Day: "6",
      Issued_On_Month: "Mayo",
      Issued_On_Year: "2021",
      Expired_On: "No caduca",
      Instructores: [
        { Instructor: "EdYoda Digital University" },
        { Instructor: "Qaifi Khan" },
        { Instructor: "Mavludin Abdulkadirov" },
      ],
      Description:
        "Este certificado garantiza que Ángel Mora Flores ha completado con éxito el curso The Complete ReactJs Course - Basics to Advanced (2021), habiendo sido impartido por EdYoda Digital University, Qaifi Khan, Mavludin Abdulkadirov en Udemy. El certificado indica que se ha completado la totalidad del curso, según lo validado por el estudiante. La duración del curso representa el total de horas de vídeo del curso en el momento de finalización más reciente.",
      Level: "No obtenido",
      Total_Hours: "3,5",
      Total_Classes: "26",
      link_name: "udemy.com/certificate",
      link_verified:
        "https://www.udemy.com/certificate/UC-78e90621-8f47-44df-a177-d42986f1737a/",
      Register_No: "UC-78e90621-8f47-44df-a177-d42986f1737a",
    },
    {
      Issuer: "Udemy",
      Title: "Modern JavaScript for React JS - ES6",
      Issued_On_Day: "26",
      Issued_On_Month: "Junio",
      Issued_On_Year: "2021",
      Expired_On: "No caduca",
      Instructores: [
        { Instructor: "EdYoda Digital University" },
        { Instructor: "Qaifi Khan" },
      ],
      Description:
        "Este certificado garantiza que Ángel Mora Flores ha completado con éxito el curso Modern JavaScript for React JS - ES6, habiendo sido impartido por EdYoda Digital University, Qaifi Khan en Udemy. El certificado indica que se ha completado la totalidad del curso, según lo validado por el estudiante. La duración del curso representa el total de horas de vídeo del curso en el momento de finalización más reciente.",
      Level: "No obtenido",
      Total_Hours: "1,5",
      Total_Classes: "16",
      link_name: "udemy.com/certificate",
      link_verified:
        "https://www.udemy.com/certificate/UC-7149eded-2ea7-4ecf-87a8-0b0cefc4ab3c/",
      Register_No: "UC-7149eded-2ea7-4ecf-87a8-0b0cefc4ab3c",
    },
    {
      Issuer: "Udemy",
      Title: "Git and GitHub Crash Course",
      Issued_On_Day: "1",
      Issued_On_Month: "Julio",
      Issued_On_Year: "2021",
      Expired_On: "No caduca",
      Instructores: [{ Instructor: "Bogdan Stashchuk" }],
      Description:
        "Este certificado garantiza que Ángel Mora Flores ha completado con éxito el curso Git and GitHub Crash Course, habiendo sido impartido por Bogdan Stashchuk en Udemy. El certificado indica que se ha completado la totalidad del curso, según lo validado por el estudiante. La duración del curso representa el total de horas de vídeo del curso en el momento de finalización más reciente.",
      Level: "No obtenido",
      Total_Hours: "1,5",
      Total_Classes: "27",
      link_name: "udemy.com/certificate",
      link_verified:
        "https://www.udemy.com/certificate/UC-5a94fd97-1607-4dbe-b9cf-740d62e8286c/",
      Register_No: "UC-5a94fd97-1607-4dbe-b9cf-740d62e8286c",
    },
  ],
  Workshops: [
    {
      Issuer: "Udemy",
      Title: "Crea un videojuego como FlappyBird desde 0",
      Issued_On_Day: "20",
      Issued_On_Month: "Julio",
      Issued_On_Year: "2023",
      Description:
        "Aprender a programar resulta fácil si entiendes la lógica detrás de cada juego además de dedicarle mucho tiempo en practicar. FlappyBird es un juego sencillo de aprender y este será el inicio para entrar al fascinante mundo del desarrollo de videojuegos.",
      Level: "No obtenido",
      Total_Hours: "1,5",
      Total_Classes: "11",
    },
    {
      Issuer: "Método SER Ágil",
      Title: "Curso Gratuito de Fundamentos de Scrum",
      Issued_On_Day: "5",
      Issued_On_Month: "Marzo",
      Issued_On_Year: "2022",
      Description:
        "El interés con este curso gratuito no es solo que te certifiques sino que puedas poner en práctica el conocimiento adquirido. El curso esta dividido en diferentes sesiones para abarcar los diferentes fundamentos.",
      Level: "No obtenido",
      Total_Hours: "7,5",
      Total_Classes: "3",
    },
    {
      Issuer: "Udemy",
      Title: "Fundamentos de ReactJs desde la documentación oficial",
      Issued_On_Day: "4",
      Issued_On_Month: "Enero",
      Issued_On_Year: "2022",
      Description:
        "Este curso lo he creado como si fuera para mí mismo, en mis inicios me hubiera gustado contar con una guía que me hubiera dado los conceptos básicos sobre React, pero sobre todo que me hubiera enseñado o mostrado el conocimiento aprendido desde la documentación oficial. Así cuando tenga dudas o inquietudes, recurrir a ella para aclararlas. También es importante decir que este curso es un curso de iniciación, veremos los conceptos básicos, pero con un proyecto de aprendizaje muy interesante, que te abrirá la mente para seguir creando tus propios proyectos.",
      Level: "No obtenido",
      Total_Hours: "1,5",
      Total_Classes: "15",
    },
    {
      Issuer: "Udemy",
      Title: "MERN Stack Authentication And Deployment",
      Issued_On_Day: "7",
      Issued_On_Month: "Octubre",
      Issued_On_Year: "2021",
      Description:
        "En este curso, aprenderemos cómo autenticar (registrar / iniciar sesión) un usuario e implementar nuestra aplicación de pila MERN en Heroku. También aprenderemos cómo proteger nuestra contraseña antes de almacenarla en la base de datos. Esta no es una introducción al curso de pila MERN, por lo que debe conocer los conceptos básicos de la pila MERN. Manejo de la autenticación con JSON Web Token, implementación en Heroku, conocimientos básicos de MERN Stack, para desarrolladores principiantes de pila de MERN.",
      Level: "No obtenido",
      Total_Hours: "1",
      Total_Classes: "5",
    },
    {
      Issuer: "Udemy",
      Title: "Las bases para desarrollar una aplicación full stack MERN",
      Issued_On_Day: "28",
      Issued_On_Month: "Septiembre",
      Issued_On_Year: "2021",
      Description:
        "En este curso introductorio en el stack MERN aprenderás a las bases o principios de una aplicación web spa usando las tecnologías del stack MERN (mongodb, express, react, nodejs). Adaptar la aquitectura MVC en nuestro backend, creando modelos, vistas y controladores. En la sección del frontend vamos a usar React y sus últimas actualizaciones, como lo son sus Hooks. Desarrollar una restful api, Crear un servidor usando express, Crear modelos, controladores y rutas, Hacer pruebas con postman, Desarrollar el frontend o cliente usando react con sus últimas actualizaciones como lo son los hooks, Sweetalert2. Desarrolladores dispuestos a aprender/repasar las bases del stack MERN.",
      Level: "No obtenido",
      Total_Hours: "1",
      Total_Classes: "9",
    },
    {
      Issuer: "Udemy",
      Title: "Aprende PHP y MySQLi, conceptos básicos para principiantes",
      Issued_On_Day: "14",
      Issued_On_Month: "Agosto",
      Issued_On_Year: "2021",
      Description:
        "Introducción a PHP de una manera rápida y sencilla, adquiriendo todos los conceptos básicos que les permitan desarrollar proyectos desde lo más básico, obteniendo las bases necesarias para proyectos de mayor complejidad. Gracias a este lenguaje han sido creados proyectos exitosos como Facebook, Wordpress, Wikipedia y muchos más. Capacidad de entender la lógica de la programación web, contaran con la habilidad de manejar datos por medio de mysqli y php, capacidad de crear sus propios proyectos de sitios dinámicos, contar con el conocimiento suficiente para continuar aprendiendo.",
      Level: "No obtenido",
      Total_Hours: "2",
      Total_Classes: "28",
    },
    {
      Issuer: "Udemy",
      Title: "Fundamentos de Programación Web para Principiantes",
      Issued_On_Day: "25",
      Issued_On_Month: "Julio",
      Issued_On_Year: "2021",
      Description:
        "Introducción a la Programación Web, Lenguajes, Frameworks, BD, Herramientas y como convertirte en Desarrollador Web. Te enseñará lo básico de convertirte en Desarrollador Web, temas como: Lenguajes de Programación web, cuales son los más populares, Diferencias entre Desarrolladores Front End y Backend, ¿Que es un framework y porque aprender uno o más?, ¿Que son las Operaciones CRUD que todo desarrollador backend debe hacer?, ¿Que son las Bases de Datos?, ¿Qué es el Hosting?, Otras herramientas como Web Developer Tools, Emuladores y servidores locales, Diseño de Interfaz de Usuario, wireframing y prototyping, Responsive Web Design, Accesibilidad y más al finalizar el curso no serás un programador web pero tendrás más claro tu camino y que debes aprender para convertirte en uno.",
      Level: "No obtenido",
      Total_Hours: "2,5",
      Total_Classes: "30",
    },
    {
      Issuer: "4Geeks Academy",
      Title: "Iníciate en Node.Js",
      Issued_On_Day: "2",
      Issued_On_Month: "Junio",
      Issued_On_Year: "2021",
      Description:
        "Introducción para tomar rumbo en NodeJS. ¿De qué se trata?, dudas sobre los siguientes temas: ¿Qué es NodeJS?, Instalación, ¿Qué es NPM?, Arquitectura de NodeJS, Principales módulos, ¿Por qué usar TypeScript?, Ecosistema. Además, resolveremos todas las dudas junto al gran experto, Manuel Ortega, Mentor Instructor de 4Geeks Academy.",
      Level: "No obtenido",
      Total_Hours: "",
      Total_Classes: "",
    },
  ],
  Pro_Practice: [
    {
      Workplace: "Laboratorio Echandi",
      Workplace_nick: "LAB ECHANDI",
      Ubication:
        "San Rafael de Escazu, 75 mts norte del McDonald, edificio esquinero.",
      telephone: "(+506) 2258-4334.",
      position: "Servicio al cliente",
      supervisor: "Rebeca Solano",
      range: "Jefactura a cargo",
      cellphone: "No obtenido",
      job_description:
        "Brindar la información relacionada con el laboratorio para dar el mejor servicio al ayudar a los pacientes con sus consultas, preparaciones para toma de muestras y cotizaciones de tarifas tanto de laboratorio como cotizaciones bajo convenios o aseguradoras, formularios, diagnósticos y coberturas del asegurado; envió de resultados de pacientes así como solicitudes de agenda y coordinación para toma de muestras a domicilio.",
      link_name: "https://labechandi.com",
      link_verified: "https://labechandi.com",
      since_On_Day: "16",
      since_On_Month: "Enero",
      since_On_Year: "2023",
      phrase: "",
      Work_here: "No",
      until_On_Day: "29",
      until_On_Month: "Septiembre",
      until_On_Year: "2023",
      links: [
        {
          icon: "fab fa-facebook-f",
          facebook: "https://www.facebook.com/LaboratoriosEchandi",
        },
      ],
    },
    {
      Workplace: "Sindicato Trabajadores del INA",
      Workplace_nick: "SITRAINA",
      Ubication: "Carvajal Castro, Heredia, San José.",
      telephone: "(+506) 2210-6200.",
      position: "Desarrollador web",
      supervisor: "Lic. Jeffrey Jiménez Chavarría.",
      range: "Docente, Instituto Nacional de Aprendizaje.",
      cellphone: "(+506) 8877-6796.",
      job_description:
        "Servicio profesional para la empresa SITRAINA encargado de su sitio web. Entre las tareas realizadas son levantamiento de requerimientos, realización de minutas, establecimiento de contrato, muestra de diseño, organización de programación y funciones, coordinación de trabajo con seguimiento del sitio web tanto principal como secundario y mantenimiento del sistema que se encuentraba bajo mi asignación.",
      link_name: "https://proyectositraina.netlify.app",
      link_verified: "https://proyectositraina.netlify.app",
      since_On_Day: "5",
      since_On_Month: "Noviembre",
      since_On_Year: "2021",
      phrase: "",
      Work_here: "No",
      until_On_Day: "18",
      until_On_Month: "Mayo",
      until_On_Year: "2023",
      links: [
        {
          icon: "fab fa-facebook-f",
          facebook: "https://www.facebook.com/SitrainaCR/",
        },
      ],
    },
    {
      Workplace: "4Geeks Academy",
      Workplace_nick: "BreathCode (4Geeks Product)",
      Ubication: "No obtenido",
      telephone: "No obtenido",
      position: "Front End",
      supervisor: "Lic. Alejandro Sanchez",
      range: "4Geeks Co-founder & Master Mentor",
      cellphone: "No obtenido",
      job_description:
        "Colaborador de Front-End bajo asignaturas de Tech SCRUM correspondientes a diferentes proyectos de la academia para mi entrenamiento, investigación, uso de diferentes herramientas como AXIOS to FETCH API, Material Design UI, Matx React, React-Toastify, muestra de avances y manejo de controlador de versiones GitHub.",
      link_name: "breatheco.de",
      // link_verified: "https://github.com/orgs/4GeeksAcademy/projects",
      link_verified: "https://4geeks.com/",
      since_On_Day: "5",
      since_On_Month: "Junio",
      since_On_Year: "2021",
      phrase: "",
      Work_here: "No",
      until_On_Day: "30",
      until_On_Month: "Agosto",
      until_On_Year: "2021",
      links: [
        {
          icon: "fab fa-facebook-f",
          facebook: "https://www.facebook.com/SitrainaCR/",
        },
      ],
    },
    {
      Workplace: "Departamento Netgear",
      Workplace_nick: "Concentrix",
      Ubication: "Av. Elena Lahmann de Rohrmoser, Zona Industrial, San José",
      telephone: "(+506) 2519-6700",
      position: "Agente de servicio al cliente",
      supervisor: "Gloriana Cabrera Chaves",
      range: "No obtenido",
      cellphone: "No obtenido",
      job_description:
        "Ayudar a los clientes que tuvieran inconvenientes con los dispositivos de red para el hogar, realizando registro de dispositivos, configuraciones iniciales, cambio de contraseñas, independización de señales de red, problemas de velocidad o intermitencia, desfragmentación de paquetes, cambio de canales, bloqueo de usuarios desconocidos y recomendaciones para uso de los dispositivos",
      link_name: "",
      link_verified: "",
      since_On_Day: "10",
      since_On_Month: "Noviembre",
      since_On_Year: "2019",
      phrase: "",
      Work_here: "No",
      until_On_Day: "10",
      until_On_Month: "Abril",
      until_On_Year: "2020",
      links: [
        {
          icon: "fab fa-facebook-f",
          facebook: "https://www.facebook.com/SitrainaCR/",
        },
      ],
    },
  ],
  Skills: [
    {
      subheading: "programacion & herramientas",
      workflow: "Habilidades Blandas",
      description: [
        {
          flujo:
            "Diseño receptivo, primero en dispositivos móviles, multifuncional.",
        },
        {
          flujo: "Desarrollo en método ágil de marco SCRUM.",
        },
        {
          flujo: "Creatividad, originalidad e iniciativa.",
        },
        {
          flujo: "Razonamiento, resolución de problemas complejos e ideación.",
        },
      ],
      links: [
        {
          name: "MONGODB",
          porcent: "60%",
          icon: "fas fa-database",
        },
        {
          name: "EXPRESSJS",
          porcent: "70%",
          icon: "fas fa-cogs",
        },
        {
          name: "REACTJS",
          porcent: "90%",
          icon: "fab fa-react",
        },
        {
          name: "NODEJS",
          porcent: "70%",
          icon: "fab fa-node",
        },
        // {
        //   name: "Requerimientos",
        //   porcent: "50%",
        //   icon: "far fa-folder",
        // },
        // {
        //   name: "Diagramas de flujo",
        //   porcent: "50%",
        //   icon: "fas fa-project-diagram",
        // },
        // {
        //   name: "Mapeo de sitios web",
        //   porcent: "50%",
        //   icon: "fas fa-sitemap",
        // },
        // {
        //   name: "Visual Studio Code",
        //   porcent: "50%",
        //   icon: "fas fa-keyboard",
        // },
        // {
        //   name: "Wireframing",
        //   porcent: "50%",
        //   icon: "far fa-file-code",
        // },
        // {
        //   name: "Prototyping",
        //   porcent: "50%",
        //   icon: "fas fa-file-code",
        // },
        // {
        //   name: "Terminal",
        //   porcent: "50%",
        //   icon: "fas fa-terminal",
        // },
        {
          name: "HTML",
          porcent: "70%",
          icon: "fab fa-html5",
        },
        {
          name: "CSS",
          porcent: "60%",
          icon: "fab fa-css3-alt",
        },
        {
          name: "Bootstrap",
          porcent: "60%",
          icon: "fab fa-bootstrap",
        },
        {
          name: "JavaScript",
          porcent: "80%",
          icon: "fab fa-js",
        },
        {
          name: "VANILLAJS",
          porcent: "80%",
          icon: "fab fa-node-js",
        },
        {
          name: "SCRUM",
          porcent: "50%",
          icon: "fas fa-hands-helping",
        },
        {
          name: "NPM",
          porcent: "50%",
          icon: "fab fa-npm",
        },
        // {
        //   name: "GITHUB",
        //   porcent: "40%",
        //   icon: "fab fa-github",
        // },
        // {
        //   name: "GITPOD",
        //   porcent: "50%",
        //   icon: "fab fa-github-square",
        // },
        {
          name: "GIT",
          porcent: "50%",
          icon: "fas fa-code-branch",
        },
        // {
        //   name: "MONGOOSE",
        //   porcent: "50%",
        //   icon: "fas fa-cog",
        // },
        // {
        //   name: "MONGODB Compass",
        //   porcent: "50%",
        //   icon: "far fa-compass",
        // },
        // {
        //   name: "MONGODB ATLAS",
        //   porcent: "50%",
        //   icon: "fas fa-cloud-upload-alt",
        // },
        // {
        //   name: "Google Analytics",
        //   porcent: "50%",
        //   icon: "fa fa-chart-line",
        // },

        // {
        //   name: "POSTMAN",
        //   porcent: "50%",
        //   icon: "fas fa-rocket",
        // },
        // {
        //   name: "Wordpress",
        //   porcent: "50%",
        //   icon: "fab fa-wordpress",
        // },
        // {
        //   name: "CPANEL",
        //   porcent: "50%",
        //   icon: "fab fa-cpanel",
        // },
      ],
    },
  ],
  Projects: [
    // {
    //   Title: "RuffWalksCR",
    //   Project_by: "RuffWalksCR",
    //   Description:
    //     "El propósito de este sitio web es ofrecer los servicios de los paseadores de perros RuffWalksCR, mostrar la informacion de empresa, sus creadores, mascotas de los clientes, asi como servicios, beneficios y promocionar de forma mas personalizada.",
    //   img: "./multimedia/proyectos/PRO_SITRAINA.gif",
    //   link: "https://proyectositraina.netlify.app",
    // },
    {
      Title: "SITRAINA",
      Project_by: "Instituto Nacional de Aprendizaje",
      Description:
        "Proyecto nuevo, continuación de proyecto final del curso de Desarrollo Web en el Instituto Nacional de Aprendizaje (INA) en el cual se migro al framework React y usando plantilla en Bootstrap, se encuentra en construcción para su total implementación. Pre visualización, en su función y primera etapa solo cuenta con algunas páginas funcionando y documentos descargables.",
      img: "./multimedia/proyectos/PRO_SITRAINA.gif",
      link: "https://proyectositraina.netlify.app",
    },
    {
      Title: "Proyecto M||RA",
      Project_by: "Instituto Nacional de Aprendizaje",
      Description:
        "El propósito de este sitio es dar a conocer las capacidades que como desarrolladores Web obtuvimos mediante un largo tiempo de estudio. La arquitectura de software se realiza API REST remota para la interacción de servicio Web en data JSON y AJAX con JavaScript. Cabe resaltar el entretenimiento del sitio Web con videos y música que incluye ideas propias de mi persona.",
      img: "./multimedia/proyectos/PRO_HTML_API_JSON.gif",
      link: "https://anmora.github.io/Practica-HTML-API-JSON/index.html",
    },
    // {
    //     Title: "Registro/Login MERN",
    //     Project_by: "AnMORA",
    //     Description: "Proyecto de aprendizaje para autenticar (registrarse/iniciar sesión) el usuario e implementar nuestra aplicación de pila MERN en Heroku. También de cómo proteger nuestra contraseña de forma encriptada antes de almacenarla en la base de datos. El sitio aún se encuentra construcción para mejoras e implementación de más datos y CRUD de ventas.",
    //     img: "./multimedia/proyectos/PRO_Register_Login.gif",
    //     link: "https://agile-plains-93591.herokuapp.com/login/"
    // },
    // {
    //     Title: "Books API App MERN",
    //     Project_by: "AnMORA",
    //     Description: "Proyecto personal de investigación y aprendizaje para sugerir libros de programación, CRUD completo, se utilizaron herramientas de interfaz Front End en ReactJS, usando Fetch API para muestra de datos remota con arquitectura de software Back End JavaScript NodeJS y uso de servicio web MongoDB ATLAS en data JSON, poniendo en práctica el conocimiento adquirido usando herramientas como Command line, NPM y servicio web Heroku.",
    //     img: "./multimedia/proyectos/PRO_StoreAllNMllRAApp.gif",
    //     link: "https://desolate-springs-29315.herokuapp.com/"
    // },
    // {
    //     Title: "Que pelis ver? MERN",
    //     Project_by: "AnMORA",
    //     Description: "Proyecto personal de investigación y aprendizaje para sugerir películas, se utilizaron herramientas de interfaz Front End en ReactJS, usando React AXIOS para API REST remota con arquitectura de software Back End JavaScript NodeJS y uso de servicio web MongoDB ATLAS en data JSON mediante consulta de recursos URI, poniendo en práctica el conocimiento adquirido usando herramientas como Command line, NPM y servicio web Heroku. El sitio aún se encuentra en mejoras.",
    //     img: "./multimedia/proyectos/Que_peli_ver.gif",
    //     link: "https://mighty-gorge-25078.herokuapp.com/"
    // },
  ],
};

export default Data;
